### ISSUE TITLE
Container not reachable from extern

### ISSUE THREAD

**Issue by JanoschDeurer** [dinkel/docker-openldap#14]
I started the container and it works fine when i link it to the phpldapadmin container. I also published port 389 to make it reachable for every container. However if I'm trying to connect to the ldap server form extern of form another container I get no response. This is my docker-compose file:

```
ldap:
  image: dinkel/openldap
  volumes:
   - ./volumes/ldap/etc_ldap:/etc/ldap
   - ./volumes/ldap/var_lib_ldap:/var/lib/ldap
  environment:
   - SLAPD_PASSWORD=<pw>
   - SLAPD_DOMAIN=<domain>
   - SLAPD_ORGANIZATION=<organization>
  ports:
   - "389:389"
phpldapadmin:
  image: dinkel/phpldapadmin
  links:
   - ldap:openldap
  environment:
   - VIRTUAL_HOST=<domain reverseproxy>
```
