### ISSUE TITLE
How can I use CourierMail ?

### ISSUE THREAD

**Issue by kbeaugrand** [dinkel/docker-openldap#17]
Hi, 

I' trying to use your image in order to provider a ldap directory with CourierMail enabled accounts. 
After having copied the authldap.config file from courier-ldap package, added my include into the ldap.conf file, I hoped that courier schemas works but not. 

#### docker-compose.yml
```
services:
   slapd:
     image: dinkel/openldap
     restart: always
     volumes:
       - "/opt/srv/slapd/data:/var/lib/ldap"
       - "/opt/srv/slapd/config:/etc/ldap"
     ports:
       - "389:389"
```
#### ldap.conf
```
include /etc/ldap/schema/authldap.schema
```

#### config directory tree
```
/opt/srv/slapd/config
|-- ldap.conf
|-- modules
| |-- memberof.ldif
| `-- ppolicy.ldif
|-- sasl2
|-- schema
| |-- authldap.schema
| |-- collective.ldif
| |-- collective.schema
| |-- corba.ldif
| |-- corba.schema
| |-- core.ldif
| |-- core.schema
| |-- cosine.ldif
| |-- cosine.schema
| |-- duaconf.ldif
| |-- duaconf.schema
| |-- dyngroup.ldif
| |-- dyngroup.schema
| |-- inetorgperson.ldif
| |-- inetorgperson.schema
| |-- java.ldif
| |-- java.schema
| |-- misc.ldif
| |-- misc.schema
| |-- nis.ldif
| |-- nis.schema
| |-- openldap.ldif
| |-- openldap.schema
| |-- pmi.ldif
| |-- pmi.schema
| |-- ppolicy.ldif
| |-- ppolicy.schema
| `-- README
`-- slapd.d
    |-- cn=config
    | |-- cn=module{0}.ldif
    | |-- cn=schema
    | | |-- cn={0}core.ldif
    | | |-- cn={1}cosine.ldif
    | | |-- cn={2}nis.ldif
    | | `-- cn={3}inetorgperson.ldif
    | |-- cn=schema.ldif
    | |-- olcBackend={0}hdb.ldif
    | |-- olcDatabase={0}config.ldif
    | |-- olcDatabase={-1}frontend.ldif
    | `-- olcDatabase={1}hdb.ldif
    `-- cn=config.ldif

6 directories, 42 files
```

How can I make other schemas than provided in you image work ? 

Regards,
